name: Build-Docker

on:
  push:
    branches:
      - master
      - main

concurrency:
  group: build-docker-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # API
  firecrawl_api:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: "apps/api/Dockerfile"
      context: "./apps/api"
      imageName: "baoduy2412/firecrawl-api"
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  # Playwright TS
  firecrawl_playwright_ts:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: "apps/playwright-service-ts/Dockerfile"
      context: "./apps/playwright-service-ts"
      imageName: "baoduy2412/firecrawl-playwright-ts"
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
