name: Build-Docker

on:
  push:
    branches:
    - master
    - main

jobs:
  # API
  firecrawl_api:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: 'api/Dockerfile'
      context: './api'
      imageName: 'baoduy2412/firecrawl-api'
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  
  # Playwright TS
  firecrawl_playwright_ts:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: 'playwright-service-ts/Dockerfile'
      context: './playwright-service-ts'
      imageName: 'baoduy2412/firecrawl-playwright-ts'
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  # Playwright TS
  firecrawl_playwright:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: 'playwright-service/Dockerfile'
      context: './playwright-service'
      imageName: 'baoduy2412/firecrawl-playwright'
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  # Playwright TS
  firecrawl_redis:
    uses: baoduy/ShareWorkflows/.github/workflows/docker-publish.yaml@main
    with:
      dockerFile: 'redis/Dockerfile'
      context: './redis'
      imageName: 'baoduy2412/firecrawl-redis'
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      
